### ISSUE TITLE
proc-macro2 relies on unwinding which `-Zno-landing-pads` breaks

### ISSUE THREAD

**Issue by leo-lb** [servo/rust-cssparser#273]
We are hitting that here:

https://github.com/stjepang/smol/pull/13/checks?check_run_id=618319573#step:4:342

I'm not really sure what's the cause yet. I'll post more details once I have them.

**Comment by leo-lb** [comment]
Looks like it may be this:

```rust
        // We have stack overflows on Servo's CI.
        let handle = Builder::new()
            .stack_size(128 * 1024 * 1024)
            .spawn(move || {
                match_byte::expand(&input, &output);
            })
            .unwrap();
```
https://github.com/servo/rust-cssparser/blob/v0.25.9/build.rs#L35

What can we do here?

**Comment by SimonSapin** [comment]
Is this a stack overflow? I can’t see the log, maybe because the repo is private. Do you have steps to reproduce?

**Comment by SimonSapin** [comment]
This build script parses an entire module with `syn` which has a recursive parser whose stack frames are apparently large-ish in debug mode. This plus a deeply-nested parse tree together caused stack overflows before, leading to the larger stack size that you see. But I thought 128 MB was a conservative over-estimate, I’m kinda surprised we’d still overflow *that*.

**Comment by leo-lb** [comment]
@SimonSapin, oh sorry I'm stupid. It's private yes but will be public soon, and it's just a SIGABRT there's nothing more interesting in the log.

What I'm thinking is that the 128MB stack size is over the runner ulimit for a stack, so it crashes when you try to raise it that big.

**Comment by leo-lb** [comment]
@SimonSapin 

Here's the Github Actions workflow file to reproduce:

```yaml
name: Code Coverage

on: [push]

jobs:
  grcov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'
      - uses: actions-rs/grcov@v0.1
```
