### ISSUE TITLE
Slashes in quoted strings result in \n (LF)

### ISSUE THREAD

**Issue by snshn** [servo/rust-cssparser#283]
This is a weird one.

Long story short, https://www.w3.org/Style/Examples/007/units.en.html has a CSS file linked https://www.w3.org/Style/CSS/w3c-2010/main that styles among other things that flags button in the top-right corner of the page.

Here's the problematic CSS rule:
```CSS
#language a[href="#translations"]:before {
  content: url(flags) "\A";
  white-space: pre }
```

The crate currently parses `\A` as `\n` (0x10, LF).

I believe it should preserve the original byte.

Part of `Token::QuotedString`.
